development:
  # Configure available database clients. (required)
  clients:
    # Defines the default client. (required)
    default:
      database: links_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: links_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
<% if ENV['MONGOLAB_MAUVE_URI'] %>
<% uri = URI.parse(ENV['MONGOLAB_MAUVE_URI']) %>
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: <%= uri.path.sub('/','') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% end %>
