# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e45fd4f74664fa0e81e114c7927c9162cb871d394212ec38b96088e7813c373918e6ac188d4254c759e3cf465ae960446e5359e173127be9df177d2d716c059
  email_login: dev.fav.links
  email_password: favoritelinks2016
test:
  secret_key_base: ee5d45f014ec8aa23834f4966347d95dcdfa7731e1aaad6ace09ed0482f7bed27f52857ce159fe52bc14f8b4ff2cde9d80634b2e0e2199117b18122d6eef58e7
  email_login: dev.fav.links
  email_password: favoritelinks2016
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_login: <%= ENV["EMAIL_LOGIN"] %>
  email_password: <%= ENV["EMAIL_PASSWORD"] %>
  host: <%= ENV["HOST"] %>
